name: islam_guide
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.1.0  
  flutter_pdfview: ^1.1.0
  path_provider: ^1.1.0
  http: ^0.12.0
  audioplayers: ^0.16.2  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_calendar_carousel: ^1.4.12
  rxdart: ^0.22.0
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  splashscreen: ^1.3.5  
  flutter_launcher_icons: ^0.7.0  

flutter_icons:
  image_path: "assets/images/icon/icon013.png"
  android: true
  ios: true  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/names/name1.png
    - assets/images/names/name2.png
    - assets/images/names/name3.png
    - assets/images/names/name4.png
    - assets/images/names/name5.png
    - assets/images/names/name6.png
    - assets/images/names/name7.png
    - assets/images/names/name8.png
    - assets/images/names/name9.png
    - assets/images/names/name10.png
    - assets/images/names/name11.png
    - assets/images/names/name12.png
    - assets/images/names/name13.png
    - assets/images/names/name14.png
    - assets/images/names/name15.png
    - assets/images/names/name16.png
    - assets/images/names/name17.png
    - assets/images/names/name18.png
    - assets/images/names/name19.png
    - assets/images/names/name20.png
    - assets/images/names/name21.png
    - assets/images/names/name22.png
    - assets/images/names/name23.png
    - assets/images/names/name24.png
    - assets/images/names/name25.png
    - assets/images/names/name26.png
    - assets/images/names/name27.png
    - assets/images/names/name28.png
    - assets/images/names/name29.png
    - assets/images/names/name30.png
    - assets/images/names/name31.png
    - assets/images/names/name32.png
    - assets/images/names/name33.png
    - assets/images/names/name34.png
    - assets/images/names/name35.png
    - assets/images/names/name36.png
    - assets/images/names/name37.png
    - assets/images/names/name38.png
    - assets/images/names/name39.png
    - assets/images/names/name40.png
    - assets/images/names/name41.png
    - assets/images/names/name42.png
    - assets/images/names/name43.png
    - assets/images/names/name44.png
    - assets/images/names/name45.png
    - assets/images/names/name46.png
    - assets/images/names/name47.png
    - assets/images/names/name48.png
    - assets/images/names/name49.png
    - assets/images/names/name50.png
    - assets/images/names/name51.png
    - assets/images/names/name52.png
    - assets/images/names/name53.png
    - assets/images/names/name54.png
    - assets/images/names/name55.png
    - assets/images/names/name56.png
    - assets/images/names/name57.png
    - assets/images/names/name58.png
    - assets/images/names/name59.png
    - assets/images/names/name60.png
    - assets/images/names/name61.png
    - assets/images/names/name62.png
    - assets/images/names/name63.png
    - assets/images/names/name64.png
    - assets/images/names/name65.png
    - assets/images/names/name66.png
    - assets/images/names/name67.png
    - assets/images/names/name68.png
    - assets/images/names/name69.png
    - assets/images/names/name70.png
    - assets/images/names/name71.png
    - assets/images/names/name72.png
    - assets/images/names/name73.png
    - assets/images/names/name74.png
    - assets/images/names/name75.png
    - assets/images/names/name76.png
    - assets/images/names/name77.png
    - assets/images/names/name78.png
    - assets/images/names/name79.png
    - assets/images/names/name80.png
    - assets/images/names/name81.png
    - assets/images/names/name82.png
    - assets/images/names/name83.png
    - assets/images/names/name84.png
    - assets/images/names/name85.png
    - assets/images/names/name86.png
    - assets/images/names/name87.png
    - assets/images/names/name88.png
    - assets/images/names/name89.png
    - assets/images/names/name90.png
    - assets/images/names/name91.png
    - assets/images/names/name92.png
    - assets/images/names/name93.png
    - assets/images/names/name94.png
    - assets/images/names/name95.png
    - assets/images/names/name96.png
    - assets/images/names/name97.png
    - assets/images/names/name98.png
    - assets/images/names/name99.png
    - assets/files/quran urdu.pdf
    - assets/files/quran english.pdf
    - assets/files/Holy-Quran-in-Arabic-Language.pdf
    - assets/files/yassarnal quran.pdf
    - assets/images/logos/hadith.png
    - assets/images/logos/quran.png
    - assets/images/logos/tasbih.png
    - assets/images/logos/namaztime.png
    - assets/images/logos/shahada.png
    - assets/images/logos/allah.png
    - assets/images/logos/calendar.png
    - assets/images/logos/dua.png
    - assets/images/logos/kalima.png
    - assets/images/plane.jpg
    - assets/images/namazimage.png
    - assets/images/home.jpg
    - assets/images/audio.jpg
    - assets/images/border01.jpg
    - assets/images/border1.jpg
    - assets/images/splash.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
